language: c
sudo: required
matrix:
  include:
    - compiler: gcc-8
    - compiler: clang
    - compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python-pip
            - g++-8
      env:
        - BUILD_TYPE=Coverage
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind libyaml-dev
script:
  - make test
  - make valgrind-quiet
  - make VARIANT=san test
  - |
    if [[ "${BUILD_TYPE}" == "Coverage" ]]; then
      sudo pip install gcovr;
      make coverage;
      find build/coverage -name "*.gc*" -type f -delete;
      bash <(curl -s https://codecov.io/bash) -X search -f build/coverage.xml;
    fi
